/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FactoryContract__factory } from "./FactoryContract__factory";
export { StorageContract__factory } from "./StorageContract__factory";
